name: release

on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ luyikk/rust1804 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
            persist-credentials: 'false'
      - name: Build Rust project in Docker
        run: |
            docker run --rm -v "$(pwd)":/workspace -w /workspace ${{ matrix.os }} /bin/bash -c "cargo build --release"
      - name: Package binary
        run: |
          mkdir -p release
          cp target/release/main release/
          tar -czvf release/main-ubuntu18.tar.gz -C release main

      - name: Upload to GitHub Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ github.event.release.upload_url }}
            asset_path: ./release/main-ubuntu18.tar.gz
            asset_name: main-ubuntu18.tar.gz
            asset_content_type: application/gzip

