name: release

on:
  push:
    tags:
      - v[0-9]+.*
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system:
          - image: luyikk/rust1804
            os: ubuntu1804
            bin: main
          - image: luyikk/rust_ubuntu
            os: ubuntu2204
            bin: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Rust project in Docker
        run: |
            docker run --rm -v "$(pwd)":/workspace -w /workspace ${{ matrix.system.image }} /bin/bash -c "cargo build --release"
      - name: Package binary
        run: |
          mkdir -p release
          cp target/release/main release/
          tar -czvf release/${{ matrix.system.bin }}-${{ matrix.system.os }}.tar.gz -C release main

      - name: Upload Binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/${{ matrix.system.bin }}-${{ matrix.system.os }}.tar.gz
